site_name: ADP8
site_description: Yet Another Autonomy Stack
site_author: MockaSort-Studio
docs_dir: docs

theme:
  name: material 
  favicon: images/favicon.png

nav:
  - Home: index.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Contributing: CONTRIBUTING.md
