name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - '**/*.md'

jobs:
  build-main:
    runs-on: ubuntu-latest
    strategy:
      #leaving it as a matrix for easy future expansion
      matrix:
        include:
          - name: "Build All"
            target: "-- //... -//ai/..."
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_environment

      - name: Bazel Build
        run: |
          bazel build --config=ci ${{ matrix.target }}