name: Main Build Status

on:
  push:
    branches:
      - main

jobs:
  setup:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/setup_environment

  build-main:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Loss Vegas"
            target: "//ai/..."
          
          - name: "Build All"
            target: "-- //... -//ai/..."
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_environment

      - name: Bazel Build
        run: |
          bazel build --config=ci ${{ matrix.target }}